development:
  adapter: postgresql
  encoding: unicode
  database: fuzz_development
  pool: 5
  username: fuzz
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fuzz_test
  pool: 5
  username: fuzz
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fuzz_production
  pool: 5
  username: fuzz
  password: